export default [
    {
      code: 'IntlBackslash',
      contents: { en: '§', ua: '\\' },
      shift: { en: '±', ua: '/' },
      character: { en: 'symbol', ua: 'letter' },
    },
    {
      code: 'Digit1',
      contents: { en: '1', ua: '1' },
      shift: { en: '!', ua: '!' },
      character: { en: 'digit', ua: 'digit' },
    },
    {
      code: 'Digit2',
      contents: { en: '2', ua: '2' },
      shift: { en: '@', ua: '"' },
      character: { en: 'digit', ua: 'digit' },
    },
    {
      code: 'Digit3',
      contents: { en: '3', ua: '3' },
      shift: { en: '#', ua: '№' },
      character: { en: 'digit', ua: 'digit' },
    },
    {
      code: 'Digit4',
      contents: { en: '4', ua: '4' },
      shift: { en: '$', ua: ';' },
      character: { en: 'digit', ua: 'digit' },
    },
    {
      code: 'Digit5',
      contents: { en: '5', ua: '5' },
      shift: { en: '%', ua: '%' },
      character: { en: 'digit', ua: 'digit' },
    },
    {
      code: 'Digit6',
      contents: { en: '6', ua: '6' },
      shift: { en: '^', ua: ':' },
      character: { en: 'digit', ua: 'digit' },
    },
    {
      code: 'Digit7',
      contents: { en: '7', ua: '7' },
      shift: { en: '&', ua: '?' },
      character: { en: 'digit', ua: 'digit' },
    },
    {
      code: 'Digit8',
      contents: { en: '8', ua: '8' },
      shift: { en: '*', ua: '*' },
      character: { en: 'digit', ua: 'digit' },
    },
    {
      code: 'Digit9',
      contents: { en: '9', ua: '9' },
      shift: { en: '(', ua: '(' },
      character: { en: 'digit', ua: 'digit' },
    },
    {
      code: 'Digit0',
      contents: { en: '0', ua: '0' },
      shift: { en: ')', ua: ')' },
      character: { en: 'digit', ua: 'digit' },
    },
    {
      code: 'Minus',
      contents: { en: '-', ua: '-' },
      shift: { en: '_', ua: '_' },
      character: { en: 'symbol', ua: 'symbol' },
    },
    {
      code: 'Equal',
      contents: { en: '=', ua: '=' },
      shift: { en: '+', ua: '+' },
      character: { en: 'symbol', ua: 'symbol' },
    },
    {
      code: 'Backspace',
      contents: { en: '⌫', ua: '⌫' },
      shift: { en: '⌫', ua: '⌫' },
      character: { en: 'func', ua: 'func' },
    },
    {
      code: 'Tab',
      contents: { en: 'Tab', ua: 'Tab' },
      shift: { en: 'Tab', ua: 'Tab' },
      character: { en: 'func', ua: 'func' },
    },
    {
      code: 'KeyQ',
      contents: { en: 'q', ua: 'й' },
      shift: { en: 'Q', ua: 'Й' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyW',
      contents: { en: 'w', ua: 'ц' },
      shift: { en: 'W', ua: 'Ц' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyE',
      contents: { en: 'e', ua: 'у' },
      shift: { en: 'E', ua: 'У' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyR',
      contents: { en: 'r', ua: 'к' },
      shift: { en: 'R', ua: 'К' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyT',
      contents: { en: 't', ua: 'е' },
      shift: { en: 'T', ua: 'Е' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyY',
      contents: { en: 'y', ua: 'н' },
      shift: { en: 'Y', ua: 'Н' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyU',
      contents: { en: 'u', ua: 'г' },
      shift: { en: 'U', ua: 'Г' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyI',
      contents: { en: 'i', ua: 'ш' },
      shift: { en: 'I', ua: 'Ш' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyO',
      contents: { en: 'o', ua: 'щ' },
      shift: { en: 'O', ua: 'Щ' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyP',
      contents: { en: 'p', ua: 'з' },
      shift: { en: 'P', ua: 'З' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'BracketLeft',
      contents: { en: '[', ua: 'х' },
      shift: { en: '{', ua: 'Х' },
      character: { en: 'symbol', ua: 'letter' },
    },
    {
      code: 'BracketRight',
      contents: { en: ']', ua: 'ї' },
      shift: { en: '}', ua: 'Ї' },
      character: { en: 'symbol', ua: 'letter' },
    },
    {
      code: 'Backslash',
      contents: { en: '\\', ua: 'ʼ' },
      shift: { en: '|', ua: '₴' },
      character: { en: 'symbol', ua: 'symbol' },
    },
    {
      code: 'Delete',
      contents: { en: 'Del', ua: 'Del' },
      shift: { en: 'Del', ua: 'Del' },
      character: { en: 'func', ua: 'func' },
    },
    {
      code: 'CapsLock',
      contents: { en: '⇪', ua: '⇪' },
      shift: { en: '⇪', ua: '⇪' },
      character: { en: 'func', ua: 'func' },
    },
    {
      code: 'KeyA',
      contents: { en: 'a', ua: 'ф' },
      shift: { en: 'A', ua: 'Ф' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyS',
      contents: { en: 's', ua: 'і' },
      shift: { en: 'S', ua: 'І' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyD',
      contents: { en: 'd', ua: 'в' },
      shift: { en: 'D', ua: 'В' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyF',
      contents: { en: 'f', ua: 'а' },
      shift: { en: 'F', ua: 'А' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyG',
      contents: { en: 'g', ua: 'п' },
      shift: { en: 'G', ua: 'П' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyH',
      contents: { en: 'h', ua: 'р' },
      shift: { en: 'H', ua: 'Р' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyJ',
      contents: { en: 'j', ua: 'о' },
      shift: { en: 'J', ua: 'О' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyK',
      contents: { en: 'k', ua: 'л' },
      shift: { en: 'K', ua: 'Л' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyL',
      contents: { en: 'l', ua: 'д' },
      shift: { en: 'L', ua: 'Д' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'Semicolon',
      contents: { en: ';', ua: 'ж' },
      shift: { en: ':', ua: 'Ж' },
      character: { en: 'symbol', ua: 'letter' },
    },
    {
      code: 'Quote',
      contents: { en: "'", ua: 'є' },
      shift: { en: '"', ua: 'Є' },
      character: { en: 'symbol', ua: 'letter' },
    },
    {
      code: 'Enter',
      contents: { en: 'Enter', ua: 'Enter' },
      shift: { en: 'Enter', ua: 'Enter' },
      character: { en: 'func', ua: 'func' },
    },
    {
      code: 'ShiftLeft',
      contents: { en: '⇧', ua: '⇧' },
      shift: { en: '⇧', ua: '⇧' },
      character: { en: 'func', ua: 'func' },
    },
    {
      code: 'Backquote',
      contents: { en: '`', ua: 'ґ' },
      shift: { en: '~', ua: 'Ґ' },
      character: { en: 'symbol', ua: 'symbol' },
    },
    {
      code: 'KeyZ',
      contents: { en: 'z', ua: 'я' },
      shift: { en: 'Z', ua: 'Я' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyX',
      contents: { en: 'x', ua: 'ч' },
      shift: { en: 'X', ua: 'Ч' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyC',
      contents: { en: 'c', ua: 'с' },
      shift: { en: 'C', ua: 'С' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyV',
      contents: { en: 'v', ua: 'м' },
      shift: { en: 'V', ua: 'М' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyB',
      contents: { en: 'b', ua: 'и' },
      shift: { en: 'B', ua: 'И' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyN',
      contents: { en: 'n', ua: 'т' },
      shift: { en: 'N', ua: 'Т' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'KeyM',
      contents: { en: 'm', ua: 'ь' },
      shift: { en: 'M', ua: 'Ь' },
      character: { en: 'letter', ua: 'letter' },
    },
    {
      code: 'Comma',
      contents: { en: ',', ua: 'б' },
      shift: { en: '<', ua: 'Б' },
      character: { en: 'symbol', ua: 'letter' },
    },
    {
      code: 'Period',
      contents: { en: '.', ua: 'ю' },
      shift: { en: '>', ua: 'Ю' },
      character: { en: 'symbol', ua: 'letter' },
    },
    {
      code: 'Slash',
      contents: { en: '/', ua: '.' },
      shift: { en: '?', ua: ',' },
      character: { en: 'symbol', ua: 'symbol' },
    },
    {
      code: 'ArrowUp',
      contents: { en: '⬆️', ua: '⬆️' },
      shift: { en: '⬆️', ua: '⬆️' },
      character: { en: 'symbol', ua: 'symbol' },
    },
    {
      code: 'ShiftRight',
      contents: { en: '⇧', ua: '⇧' },
      shift: { en: '⇧', ua: '⇧' },
      character: { en: 'func', ua: 'func' },
    },
    {
      code: "Fn",
      contents: { en: 'Fn', ua: 'Fn' },
      shift: { en: 'Fn', ua: 'Fn' },
      character: { en: 'func', ua: 'func' },
    },
    {
      code: 'ControlLeft',
      contents: { en: 'Ctrl', ua: 'Ctrl' },
      shift: { en: 'Ctrl', ua: 'Ctrl' },
      character: { en: 'func', ua: 'func' },
    },
    {
      code: 'AltLeft',
      contents: { en: 'Option', ua: 'Option' },
      shift: { en: 'Option', ua: 'Option' },
      character: { en: 'func', ua: 'func' },
    },
    {
      code: 'MetaLeft',
      contents: { en: '⌘', ua: '⌘' },
      shift: { en: '⌘', ua: '⌘' },
      character: { en: 'func', ua: 'func' },
      
    },
    {
      code: 'Space',
      contents: { en: ' ', ua: ' ' },
      shift: { en: ' ', ua: ' ' },
      character: { en: 'symbol', ua: 'symbol' },
    },
    {
      code: 'MetaRight',
      contents: { en: '⌘', ua: '⌘' },
      shift: { en: '⌘', ua: '⌘' },
      character: { en: 'func', ua: 'func' },
      
    },
    {
      code: 'AltRight',
      contents: { en: 'Option', ua: 'Option' },
      shift: { en: 'Option', ua: 'Option' },
      character: { en: 'func', ua: 'func' },
    },
    {
      code: 'ArrowLeft',
      contents: { en: '⬅️', ua: '⬅️' },
      shift: { en: '⬅️', ua: '⬅️' },
      character: { en: 'symbol', ua: 'symbol' },
    },
    {
      code: 'ArrowDown',
      contents: { en: '⬇️', ua: '⬇️' },
      shift: { en: '⬇️', ua: '⬇️' },
      character: { en: 'symbol', ua: 'symbol' },
    },
    {
      code: 'ArrowRight',
      contents: { en: '➡️', ua: '➡️' },
      shift: { en: '➡️', ua: '➡️' },
      character: { en: 'symbol', ua: 'symbol' },
    },
  ];
  
  